<?php

namespace EcommerceBundle\InvoiceBundle;

use EcommerceBundle\InvoiceBundle\DependencyInjection\EcommerceBundleSonataInvoiceExtension;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://symfony.com/doc/current/book/bundles.html
 */
class EcommerceBundleSonataInvoiceBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataInvoiceBundle';
    }

    public function getContainerExtension()
    {
        return new EcommerceBundleSonataInvoiceExtension();
    }
}