<?php

namespace EcommerceBundle\CustomerBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;


/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    /**
     * Check if User Address Data isset in Database
     *
     * @param User $user
     */
    public function getAddressByUserAndConditions(User $user)
    {

    }
}
