<?php

namespace EcommerceBundle\MediaBundle;

use EcommerceBundle\MediaBundle\DependencyInjection\Compiler\OverrideMediaCompilerPass;
use EcommerceBundle\MediaBundle\DependencyInjection\EcommerceBundleSonataMediaExtension;
use Sonata\MediaBundle\SonataMediaBundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://symfony.com/doc/current/book/bundles.html
 */
class EcommerceBundleSonataMediaBundle extends SonataMediaBundle
{
    /*public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new OverrideMediaCompilerPass());
    }*/

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataMediaBundle';
    }

    public function getContainerExtension()
    {
        return new EcommerceBundleSonataMediaExtension();
    }
}