<?php

namespace AppBundle\Repository;

/**
 * CellarStepDecideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CellarStepDecideRepository extends \Doctrine\ORM\EntityRepository
{
}
