<?php

namespace AppBundle\Repository;

/**
 * StepDecideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldStepDecideRepository extends \Doctrine\ORM\EntityRepository
{
}
