<?php

namespace AppBundle\Repository;

/**
 * FieldStepTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldStepTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
