<?php

namespace AppBundle\Repository;

/**
 * GroupTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
