<?php

namespace AppBundle\Repository;

/**
 * IconsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconsRepository extends \Doctrine\ORM\EntityRepository
{
}
