<?php

namespace AppBundle\Repository;

/**
 * ProductionRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionRecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByQueryName($query) {
        return $items = $this->createQueryBuilder('w')
            ->where('w.title LIKE :query')
            ->setParameter('query', '%'.$query.'%')
            ->getQuery()
            ->getResult();
    }
}
