<?php

namespace AppBundle\Repository;

/**
 * StepConstructorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
