<?php

namespace AppBundle\Repository;

/**
 * UserTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
