<?php
namespace AppBundle\Repository;

/**
 * VineyardTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VineyardTranslationRepository extends \Doctrine\ORM\EntityRepository
{

}
