<?php
namespace AppBundle\Repository;

/**
 * VineyardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VineyardRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVineyardsByWine($wineId)
    {
        $qb = $this->createQueryBuilder("v")
            ->where(':wine MEMBER OF v.wines')
            ->setParameters(array('wine' => $wineId))
            ->getQuery()
            ->getResult();
        return $qb;
    }
}
