<?php

namespace AppBundle\Repository;

/**
 * WineProductTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineProductTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}