<?php

namespace AppBundle\Repository;

use Sonata\ProductBundle\Repository\BaseProductRepository as BaseRepository;

/**
 * WineProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineProductRepository extends BaseRepository
{
}
