<?php

namespace AppBundle\Repository;

/**
 * WineryFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineryFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
