<?php

namespace AppBundle\Repository;

/**
 * WineConstructorTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineConstructorTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
