<?php

namespace AppBundle\Repository;

/**
 * WineryFieldStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineryFieldStepRepository extends \Doctrine\ORM\EntityRepository
{
}
