<?php

namespace AppBundle\Repository;

/**
 * WineConstructorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineConstructorRepository extends \Doctrine\ORM\EntityRepository
{
}
