<?php

namespace AppBundle\Repository;

/**
 * WineryCellarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineryCellarRepository extends \Doctrine\ORM\EntityRepository
{
}
