<?php

namespace AppBundle\Repository;

/**
 * WineryCellarStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineryCellarStepRepository extends \Doctrine\ORM\EntityRepository
{
}
