<?php

namespace EcommerceBundle\BasketBundle;

use Sonata\CoreBundle\Form\FormHelper;
use Sonata\BasketBundle\Form\AddressType;
use Sonata\BasketBundle\Form\ApiBasketElementParentType;
use Sonata\BasketBundle\Form\ApiBasketElementType;
use Sonata\BasketBundle\Form\ApiBasketParentType;
use Sonata\BasketBundle\Form\ApiBasketType;
use Sonata\BasketBundle\Form\BasketType;
use Sonata\BasketBundle\Form\PaymentType;
use Sonata\BasketBundle\Form\ShippingType;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use EcommerceBundle\BasketBundle\DependencyInjection\EcommerceBundleSonataBasketExtension;
use EcommerceBundle\BasketBundle\DependencyInjection\Compiler\EcommerceBundleGlobalVariableCompilerPass;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://symfony.com/doc/current/book/bundles.html
 */
class EcommerceBundleSonataBasketBundle extends Bundle
{

    /**
     * {@inheritdoc}
     */
    public function build(ContainerBuilder $container): void
    {
        $container->addCompilerPass(new EcommerceBundleGlobalVariableCompilerPass());

        $this->registerFormMapping();
    }
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'SonataBasketBundle';
    }

    public function getContainerExtension()
    {
        return new EcommerceBundleSonataBasketExtension();
    }
    /**
     * Register form mapping information.
     */
    public function registerFormMapping(): void
    {
        FormHelper::registerFormTypeMapping([
            'sonata_basket_basket' => BasketType::class,
            'sonata_basket_address' => AddressType::class,
            'sonata_basket_shipping' => ShippingType::class,
            'sonata_basket_payment' => PaymentType::class,
            'sonata_basket_api_form_basket' => ApiBasketType::class,
            'sonata_basket_api_form_basket_element' => ApiBasketElementType::class,
            'sonata_basket_api_form_basket_parent' => ApiBasketParentType::class,
            'sonata_basket_api_form_basket_element_parent' => ApiBasketElementParentType::class,
        ]);
    }
}